# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2a07a0376efcfd207ffb251c0ef4746326b5a9c55f62975851eb307e8e7bee06f8166a9a703ef22dc8e728c2a36d10a9e382bdd5ad3ff4467371d2ffe9cb711

test:
  secret_key_base: da15ae14a151d038022ca1b7d224d8ebf1bdba3410d6195cef2de3d6d6f425f5a7d0e76153fe5d357531894d93adfdd0e261a5a9f1d005da3b6f5573f59745ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
